/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  promesasSidebar: [
    {
      type: "category",
      label: "Promesas",
      link: {
        type: "generated-index",
        description: "¿Sabes que son las promesas?",
      },

      items: [
        {
          type: "category",
          label: "¿Qué es una promesa?",
          link: {
            type: "doc",
            id: "promesas/introduccion",
          },
          items: [{ type: "autogenerated", dirName: "promesas/promesas" }],
        },
        {
          type: "category",
          label: "Promesas en cadena",
          link: {
            type: "doc",
            id: "promesas/cadena",
          },
          items: [{ type: "autogenerated", dirName: "promesas/cadena" }],
        },
        {
          type: "category",
          label: "Promise All",
          link: {
            type: "doc",
            id: "promesas/promise-all",
          },
          items: [{ type: "autogenerated", dirName: "promesas/promise-all" }],
        },

        {
          type: "category",
          label: "Promise Race",
          link: {
            type: "doc",
            id: "promesas/promise-race",
          },
          items: [{ type: "autogenerated", dirName: "promesas/promise-race" }],
        },
        
      ],
    },
  ],

  fetchApiSidebar: [
    {
      type: "category",
      label: "Fetch API",
      link: {
        type: "generated-index",
        description: "¿Sabes que son las promesas?",
      },

      items: [
        {
          type: "category",
          label: "¿Que es Fetch?",
          link: {
            type: "doc",
            id: "fetch-API/introduccion",
          },
          items: [
            { type: "autogenerated", dirName: "fetch-API/fetch" },
          ],
        },

        {
          type: "category",
          label: "Solicitudes GET",
          link: {
            type: "doc",
            id: "fetch-API/get-requests",
          },
          items: [
            { type: "autogenerated", dirName: "fetch-API/get-requests"},
          ],
        },
        {
          type: "category",
          label: "Solicitudes con POST",
          link: {
            type: "doc",
            id: "fetch-API/post-requests",
          },
          items: [
            { type: "autogenerated", dirName:  "fetch-API/post-requests" },
          ],
        },
        {
          type: "category",
          label: "Fetch de blobs",
          link: {
            type: "doc",
            id: "fetch-API/fetch-blobs",
          },
          items: [
            { type: "autogenerated", dirName: "fetch-API/fetch-blobs", },
          ],
        },


      
      ],
    },
  ],

  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
